-- DDL generated by Postico 1.5.20
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE games (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    slug text UNIQUE,
    created_at timestamp without time zone DEFAULT now()
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX rooms_pkey ON games(id int4_ops);
CREATE UNIQUE INDEX rooms_slug_key ON games(slug text_ops);

-- DDL generated by Postico 1.5.20
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE cards (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    imgix_path text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX cards_pkey ON cards(id int4_ops);

-- DDL generated by Postico 1.5.20
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE avatars (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    imgix_path text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX avatars_pkey ON avatars(id int4_ops);

-- DDL generated by Postico 1.5.20
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE players (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name text,
    player_id uuid NOT NULL DEFAULT uuid_generate_v4() UNIQUE,
    created_at timestamp without time zone DEFAULT now(),
    avatar_id integer REFERENCES avatars(id)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX players_pkey ON players(id int4_ops);
CREATE UNIQUE INDEX players_uuid_key ON players(player_id uuid_ops);

-- DDL generated by Postico 1.5.20
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE player_games (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    game_slug text REFERENCES games(slug),
    score integer DEFAULT 0,
    player_id uuid REFERENCES players(player_id),
    created_at timestamp without time zone DEFAULT now()
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX player_games_pkey ON player_games(id int4_ops);

-- DDL generated by Postico 1.5.20
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE rounds (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    game_slug text REFERENCES games(slug),
    clue text,
    created_at timestamp without time zone DEFAULT now(),
    completed_at timestamp without time zone,
    player_storyteller uuid REFERENCES players(player_id)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX rounds_pkey ON rounds(id int4_ops);

-- DDL generated by Postico 1.5.20
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE hands (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    player_games_id integer REFERENCES player_games(id),
    card_id integer REFERENCES cards(id),
    created_at timestamp without time zone DEFAULT now(),
    played_at timestamp without time zone,
    round_id integer REFERENCES rounds(id)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX hands_pkey ON hands(id int4_ops);

-- DDL generated by Postico 1.5.20
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE votes (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    round_id integer REFERENCES rounds(id),
    voter_player_games_id integer REFERENCES player_games(id),
    submitter_player_games_id integer REFERENCES player_games(id),
    created_at timestamp without time zone DEFAULT now()
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX votes_pkey ON votes(id int4_ops);

