-- DDL generated by Postico 1.5.20
-- Not all database features are supported. Do not use for backup.

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS avatars (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    imgix_path text
);

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS cards (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    imgix_path text
);

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS games (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    slug text UNIQUE,
    created_at timestamp without time zone DEFAULT now()
);

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS games_old (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    room_slug text NOT NULL REFERENCES games(slug),
    points_to_win integer NOT NULL DEFAULT 30,
    created_at timestamp without time zone DEFAULT now()
);

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS migrations (
    id SERIAL PRIMARY KEY,
    name character varying(255) NOT NULL,
    run_on timestamp without time zone NOT NULL
);

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS players (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name text,
    player_id uuid NOT NULL DEFAULT uuid_generate_v4() UNIQUE,
    created_at timestamp without time zone DEFAULT now(),
    avatar_id integer REFERENCES avatars(id)
);

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS player_games (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    game_slug text REFERENCES games(slug),
    score integer DEFAULT 30,
    player_id uuid REFERENCES players(player_id),
    created_at timestamp without time zone DEFAULT now()
);

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS rounds (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    game_id integer REFERENCES games(id),
    storyteller_id integer REFERENCES player_games(id),
    clue text,
    created_at timestamp without time zone DEFAULT now()
);

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS hands (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    player_game_id integer REFERENCES player_games(id),
    card_id integer REFERENCES cards(id),
    created_at timestamp without time zone DEFAULT now(),
    played_at timestamp without time zone DEFAULT now(),
    round_id integer REFERENCES rounds(id)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS avatars_pkey ON avatars(id int4_ops);
CREATE UNIQUE INDEX IF NOT EXISTS hands_pkey ON hands(id int4_ops);
CREATE UNIQUE INDEX IF NOT EXISTS players_pkey ON players(id int4_ops);
CREATE UNIQUE INDEX IF NOT EXISTS players_uuid_key ON players(player_id uuid_ops);
CREATE UNIQUE INDEX IF NOT EXISTS player_games_pkey ON player_games(id int4_ops);
CREATE UNIQUE INDEX IF NOT EXISTS rooms_pkey ON games(id int4_ops);
CREATE UNIQUE INDEX IF NOT EXISTS rooms_slug_key ON games(slug text_ops);
CREATE UNIQUE INDEX IF NOT EXISTS cards_pkey ON cards(id int4_ops);
CREATE UNIQUE INDEX IF NOT EXISTS games_pkey ON games_old(id int4_ops);
CREATE UNIQUE INDEX IF NOT EXISTS migrations_pkey ON migrations(id int4_ops);
